
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcvebyrtauwjfvpytdyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjdmVieXJ0YXV3amZ2cHl0ZHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NjAzOTksImV4cCI6MjA1NzAzNjM5OX0.XfBfMgK6suHLa4EqEYF_P5h6GHoIgc6IzKRzVrnjg8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof window !== 'undefined' ? localStorage : undefined,
  }
});

// Helper function to handle Supabase errors more gracefully
export const handleSupabaseError = (error: any) => {
  console.error('Supabase Error:', error);
  
  // Return a user-friendly error message
  return {
    message: error?.message || 'An unexpected error occurred',
    status: error?.status || 500,
    details: error?.details || null
  };
};
